apiVersion: v1
kind: Namespace
metadata:
  name: optional3
  labels:
    training: block3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: optional3
  labels:
    training: block3
spec:
  replicas: 1
  selector:
    matchLabels:
      training: block3
  template:
    metadata:
      labels:
        training: block3
    spec:
      containers:
        - name: application
          image: quay.io/drsylent/cubix/block3/optional:quarkus3
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: FILE_LOCATION
              value: /deployments/optional.txt
          resources:
            limits:
              memory: 256Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.5"

---

apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: optional3
  labels:
    training: block3
spec:
  selector:
    training: block3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application
  namespace: optional3
  labels:
    training: block3
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: application
                port:
                  number: 8080
