apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: optional3
  labels:
    training: block3
spec:
  replicas: 1
  selector:
    matchLabels:
      training: block3
  template:
    metadata:
      labels:
        training: block3
    spec:
      containers:
        - name: application
          image: quay.io/drsylent/cubix/block3/optional:quarkus3
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: FILE_LOCATION
              value: /deployments/optional.txt
          resources:
            limits:
              memory: 256Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.5"
