apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: optional3
  labels:
    training: block3
spec:
  selector:
    training: block3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: web
